/**
 * src/steps/commit-push.ts — Commit & Push step (FR-009)
 *
 * Eighth node in the standard blueprint. Responsible for:
 *  1. Checking git status — if clean, return noop (nothing to commit)
 *  2. Staging all changes: git add .
 *  3. Committing with a formatted message: "{prefix} {task description}"
 *  4. Optionally pushing to origin/{branch} if autoPush is enabled
 *  5. Creating a GitHub PR via Octokit after push if GITHUB_TOKEN is set (D5)
 *
 * Returns a StepResult with:
 *  - data.branch  — current branch name
 *  - data.sha     — commit SHA (from simple-git response)
 *  - data.noop    — true if there was nothing to commit
 *  - data.prUrl   — GitHub PR URL (present when PR creation succeeded)
 */

import { simpleGit } from "simple-git";
import type { RunContext, StepResult, PRSummary } from "../types.js";
import { createGitHubPR } from "../reporting/pr-summary.js";

const DEFAULT_COMMIT_PREFIX = "[agent]";

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Parse GitHub owner and repo name from an HTTPS or SSH remote URL.
 * Returns null when the URL doesn't look like a GitHub URL.
 *
 * Handles:
 *  - https://github.com/owner/repo.git
 *  - git@github.com:owner/repo.git
 */
function parseGitHubOwnerRepo(remoteUrl: string): { owner: string; repo: string } | null {
  const match = remoteUrl.trim().match(/github\.com[/:]([^/\s]+)\/([^/\s.]+)/);
  if (!match) return null;
  return { owner: match[1]!, repo: match[2]!.replace(/\.git$/, "") };
}

/**
 * Build a minimal PR body for a newly-pushed agent branch.
 * A richer body (with metrics, test results, diff table) is added by T067
 * once the full reporting pipeline is in place.
 */
function buildMinimalPRBody(taskDescription: string): string {
  return [
    "## Summary",
    taskDescription,
    "",
    "---",
    "*Generated by [one-shot-agent](https://github.com/user/1shot-e2e-coding-agent) — an unattended coding agent powered by Pi SDK*",
  ].join("\n");
}

/**
 * Attempt to create a GitHub PR after pushing. Only runs when GITHUB_TOKEN
 * is present in the environment. Any error is swallowed so it never fails the
 * step — the push is the critical operation, the PR is best-effort here.
 */
async function tryCreatePR(
  ctx: RunContext,
  git: ReturnType<typeof simpleGit>,
): Promise<string | null> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) return null;

  try {
    const remoteUrl = String(await git.remote(["get-url", "origin"])).trim();
    const parsed = parseGitHubOwnerRepo(remoteUrl);
    if (!parsed) return null;

    const baseBranch = ctx.config.git?.baseBranch ?? "main";
    const summary: PRSummary = {
      title: `[agent] ${ctx.task.description}`,
      body: buildMinimalPRBody(ctx.task.description),
      baseBranch,
      headBranch: ctx.branch,
    };

    return await createGitHubPR(summary, token, parsed.owner, parsed.repo);
  } catch {
    // PR creation is best-effort — don't fail the step
    return null;
  }
}

// ─── Step ─────────────────────────────────────────────────────────────────────

export async function commitPushStep(ctx: RunContext): Promise<StepResult> {
  const git = simpleGit(ctx.workspacePath);
  const prefix = ctx.config.git?.commitMessagePrefix ?? DEFAULT_COMMIT_PREFIX;
  const autoPush = ctx.config.git?.autoPush ?? true;
  const branch = ctx.branch;

  try {
    // ── 1. Check if there is anything to commit ────────────────────────────
    const status = await git.status();
    if (status.isClean()) {
      return {
        status: "passed",
        data: { branch, noop: true },
      };
    }

    // ── 2. Stage all changes ───────────────────────────────────────────────
    await git.add(".");

    // ── 3. Commit ──────────────────────────────────────────────────────────
    const commitMessage = `${prefix} ${ctx.task.description}`;
    const commitResult = await git.commit(commitMessage);
    const sha = commitResult.commit ?? "";

    // ── 4. Push (optional) ─────────────────────────────────────────────────
    if (autoPush) {
      await git.push("origin", branch, ["--set-upstream"]);
    }

    // ── 5. Create GitHub PR (best-effort, only when GITHUB_TOKEN is set) ───
    const prUrl = autoPush ? await tryCreatePR(ctx, git) : null;

    return {
      status: "passed",
      data: { branch, sha, noop: false, ...(prUrl ? { prUrl } : {}) },
    };
  } catch (err) {
    return {
      status: "error",
      error: err instanceof Error ? err.message : String(err),
    };
  }
}


