/**
 * src/reporting/pr-summary.ts — PR summary generation (FR-009, R4)
 *
 * Generates the structured GitHub PR title and body (data-model.md Entity 10,
 * cli-contract.md "GitHub PR Contract"). Creates the PR via Octokit.
 *
 * Implementation task: T064
 */

import { Octokit } from "@octokit/rest";
import type { RunReport, PRSummary, AgentConfig, FileChange } from "../types.js";

// ─── Body helpers ──────────────────────────────────────────────────────────────

function buildChangesTable(filesChanged: FileChange[]): string {
  if (filesChanged.length === 0) {
    return "_No files changed._";
  }
  const header = "| File | Action | +Lines | -Lines |\n|------|--------|--------|--------|";
  const rows = filesChanged
    .map(
      (f) =>
        `| ${f.path} | ${f.action.charAt(0).toUpperCase() + f.action.slice(1)} | +${f.linesAdded} | -${f.linesRemoved} |`,
    )
    .join("\n");
  return `${header}\n${rows}`;
}

function buildBody(
  report: RunReport,
  provider: string,
  model: string,
  retryCount: number,
): string {
  const { testResults, lintClean } = report;
  const lintStatus = lintClean ? "✅ Clean" : "❌ Issues found";
  const cost = report.estimatedCostUsd.toFixed(2);

  return [
    "## Summary",
    report.task,
    "",
    "## Changes",
    buildChangesTable(report.filesChanged),
    "",
    "## Test Results",
    `- **${testResults.passed} passed**, ${testResults.failed} failed, ${testResults.skipped} skipped`,
    `- Lint: ${lintStatus}`,
    "",
    "## Agent Run Details",
    `- **Provider**: ${provider} / ${model}`,
    `- **Tokens**: ${report.totalTokens.toLocaleString()}`,
    `- **Cost**: $${cost}`,
    `- **Duration**: ${report.durationSeconds}s`,
    `- **Retries**: ${retryCount}`,
    "",
    "---",
    "*Generated by [one-shot-agent](https://github.com/user/1shot-e2e-coding-agent) — an unattended coding agent powered by Pi SDK*",
  ].join("\n");
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate a structured PRSummary from a RunReport and runtime details.
 *
 * @param report     - Completed run report with all metrics.
 * @param config     - Agent config (provides git.baseBranch).
 * @param headBranch - The source branch to open the PR from.
 * @param provider   - LLM provider that ran the task (e.g. "anthropic").
 * @param model      - LLM model that ran the task (e.g. "claude-sonnet-4-20250514").
 * @param retryCount - Number of fix-failures retries that were needed.
 */
export function generatePRSummary(
  report: RunReport,
  config: AgentConfig,
  headBranch: string,
  provider: string,
  model: string,
  retryCount: number,
): PRSummary {
  const baseBranch = config.git?.baseBranch ?? "main";

  return {
    title: `[agent] ${report.task}`,
    body: buildBody(report, provider, model, retryCount),
    baseBranch,
    headBranch,
  };
}

/**
 * Create a GitHub pull request via Octokit and return its HTML URL.
 *
 * @param summary  - The PRSummary to post.
 * @param token    - GitHub personal access token.
 * @param owner    - Repository owner (user or org).
 * @param repoName - Repository name.
 */
export async function createGitHubPR(
  summary: PRSummary,
  token: string,
  owner: string,
  repoName: string,
): Promise<string> {
  const octokit = new Octokit({ auth: token });
  const response = await octokit.rest.pulls.create({
    owner,
    repo: repoName,
    title: summary.title,
    body: summary.body,
    head: summary.headBranch,
    base: summary.baseBranch,
  });
  return response.data.html_url;
}
